version: "3.8"
services:
  julian-web:
    build: .
    container_name: julian-web
    networks:
      - backend
    expose:
      - 80
    restart: always
    environment:
      - VIRTUAL_HOST=www.julianschroeter.com,julianschroeter.com
      - LETSENCRYPT_HOST=www.julianschroeter.com,julianschroeter.com
      - LETSENCRYPT_EMAIL=julianschroeter@outlook.com
networks:
  backend: