version: "3.8"
services:
  julian-web:
    build: .
    container_name: julian-web
    environment:
      - VIRTUAL_HOST=www.julianschroeter.com,julianschroeter.com
      - LETSENCRYPT_HOST=www.julianschroeter.com,julianschroeter.com
      - LETSENCRYPT_EMAIL=julianschroeter@outlook.com
    restart: always