version: "3.8"
services:
  nginx-web:
    image: nginx:alpine
    container_name: julian-web
    networks:
      - backend
    expose:
      - "80"
    restart: always
    environment:
      - VIRTUAL_HOST=www.julianschroeter.com,julianschroeter.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=www.julianschroeter.com,julianschroeter.com
      - LETSENCRYPT_EMAIL=julianschroeter@outlook.com
    volumes:
      - ./public-html/:/usr/share/nginx/html:ro
networks:
  backend: